// Explicit formula trees avoid guessing where a fraction starts in prose.
const row=(...args)=>({kind:'row',args});
const frac=(a,b)=>({kind:'frac',args:[a,b]});
const pow=(a,b)=>({kind:'pow',args:[a,b]});
const root=a=>({kind:'root',args:[a]});
const sub=(a,b)=>({kind:'sub',args:[a,b]});
const bracket=a=>row('(',a,')');
const log=(base,x)=>row(sub('log',base),' ',x);
const formula=(label,expression)=>({label,expression});
const group=(note,...items)=>({note,items});
const F=frac,P=pow,R=row;

export const formulaGroups={
  '抽公因式':group('每項都要除以抽出的共同乘數；乘回去可檢查。',
    formula('分配律',R('ab + ac = a(b + c)'))),
  '平方差與完全平方':group('A、B 可以是數字，也可以是整個式子。',
    formula('平方差',R('A² − B² = (A + B)(A − B)')),
    formula('完全平方（加）',R('(A + B)² = A² + 2AB + B²')),
    formula('完全平方（減）',R('(A − B)² = A² − 2AB + B²'))),
  '二次三項式':group('先乘開再比較。p、q 要同時符合相加及相乘的條件。',
    formula('首項是 x² 時',R('(x + p)(x + q) = x² + (p + q)x + pq'))),
  '分組與利用前題':group('把重複出現的整個括號當成共同乘數。',
    formula('抽共同括號',R('AB + CB = (A + C)B'))),
  '拆分平面圖形':group('高必須與所選底邊垂直；r 是圓的半徑。所有長度先統一單位。',
    formula('三角形面積',F('底 × 高','2')),
    formula('梯形面積',F('(上底 + 下底) × 高','2')),
    formula('平行四邊形面積',R('底 × 高')),
    formula('圓面積',R('πr²'))),
  '底面積與垂直高':group('V 是體積，r 是半徑，h 是垂直高。錐體包括角錐及圓錐。',
    formula('柱體',R('V = 底面積 × h')),
    formula('圓柱',R('V = πr²h')),
    formula('錐體',R('V = ',F('底面積 × h','3'))),
    formula('圓錐',R('V = ',F('πr²h','3')))),
  '列清外露表面':group('r 是半徑，h 是垂直高，l 是圓錐斜高。總表面面積包括底面；無蓋或貼合的部分要按題意扣除。',
    formula('圓柱曲面面積',R('2πrh')),
    formula('圓柱總表面面積',R('2πr² + 2πrh')),
    formula('圓錐曲面面積',R('πrl')),
    formula('圓錐總表面面積',R('πr² + πrl'))),
  '斜率與直線':group('兩點是 (x₁,y₁)、(x₂,y₂)。斜率公式要求 x₂ ≠ x₁；平行及垂直的斜率關係只適用於兩線都有斜率時。',
    formula('斜率',R('m = ',F('y₂ − y₁','x₂ − x₁'))),
    formula('經過一點的直線',R('y − y₁ = m(x − x₁)')),
    formula('平行線',R('m₁ = m₂')),
    formula('垂直線',R('m₁m₂ = −1'))),
  '整理為零再求根':group('先寫成 ax² + bx + c = 0，a ≠ 0。根號內須 ≥ 0 才有實數答案；± 表示加、減各算一次。',
    formula('求根公式',R('x = ',F(R('−b ± ',root('b² − 4ac')),'2a')))),
  '判別式與等根':group('先整理成 ax² + bx + c = 0，a ≠ 0。Δ 讀作「delta」，用來判斷實數答案的數目。',
    formula('判別式',R('Δ = b² − 4ac')),
    formula('兩個不同實根',R('Δ > 0')),
    formula('等根',R('Δ = 0')),
    formula('沒有實根',R('Δ < 0'))),
  '先找對應邊':group('A、B 必須相似；分子始終用 A，分母始終用 B。相似立體的表面面積也用二次方。球與圓柱不相似，不能直接套用。',
    formula('面積比＝邊長比的二次方',R(F('A 的面積','B 的面積'),' = ',P(bracket(F('A 的邊長','B 的對應邊長')),'2'))),
    formula('體積比＝邊長比的三次方',R(F('A 的體積','B 的體積'),' = ',P(bracket(F('A 的邊長','B 的對應邊長')),'3'))),
    formula('例：邊長比是 2/3',R(P(bracket(F('2','3')),'2'),' = ',F('4','9'),'；',P(bracket(F('2','3')),'3'),' = ',F('8','27')))),
  '辨認斜邊':group('只適用於直角三角形。c 是直角對面的斜邊，a、b 是另外兩邊。',
    formula('畢氏定理',R('a² + b² = c²')),
    formula('求斜邊長',R('c = ',root('a² + b²')))),
  '配方找圓心':group('圓心是 (a,b)，半徑 r > 0。注意括號內是減號。',
    formula('圓的方程',R('(x − a)² + (y − b)² = r²')),
    formula('配方',R('x² + 2ax = (x + a)² − a²'))),
  '整數與負指數':group('以下 m、n 為整數；含除法或負次方時，底數不可為 0。',
    formula('同底相乘',R(P('a','m'),' × ',P('a','n'),' = ',P('a','m + n'))),
    formula('同底相除',R(F(P('a','m'),P('a','n')),' = ',P('a','m − n'))),
    formula('次方再取次方',R(P(bracket(P('a','m')),'n'),' = ',P('a','mn'))),
    formula('負次方',R(P('a','−n'),' = ',F('1',P('a','n'))))),
  '分數指數與根式':group('這裏 a > 0，m、n 為正整數。先開 n 次根，再取 m 次方。',
    formula('分數次方',R(P('a',F('m','n')),' = ',P({kind:'nthRoot',args:['a','n']},'m'))),
    formula('負的分數次方',R(P('a',R('−',F('m','n'))),' = ',F('1',P('a',F('m','n')))))),
  '同底指數方程':group('a > 0 且 a ≠ 1，才可直接比較次方。',
    formula('同底比較',R(P('a','u'),' = ',P('a','v'),' ⇔ u = v'))),
  '定義與指數互換':group('a 是底數，a > 0 且 a ≠ 1；b > 0。意思是「a 的幾次方等於 b？」',
    formula('對數與指數互換',R(log('a','b'),' = c ⇔ ',P('a','c'),' = b'))),
  '合併與拆開對數':group('底數 a 相同，a > 0 且 a ≠ 1；M、N 都要 > 0。',
    formula('相加變相乘',R(log('a','M'),' + ',log('a','N'),' = ',log('a','(MN)'))),
    formula('相減變相除',R(log('a','M'),' − ',log('a','N'),' = ',log('a',bracket(F('M','N'))))),
    formula('乘數變次方',R('k ',log('a','M'),' = ',log('a',P('M','k'))))),
  '方程與真數限制':group('a > 0 且 a ≠ 1。每一個原來的 log 後面的式子都必須 > 0，不能只檢查合併後的式子。',
    formula('把 log 方程換成指數',R(log('a','M'),' = c ⇔ M = ',P('a','c')))),
  '換底與代換':group('a、c 都 > 0 且不等於 1；b > 0。原底數 a 放在分母的 log 裏。',
    formula('換底公式',R(log('a','b'),' = ',F(log('c','b'),log('c','a'))))),
  '對數坐標與直線':group('例如兩軸同用底數 a：a > 0、a ≠ 1，x、y > 0。m 是斜率，c 是直線的縱截距。',
    formula('先把整個 log 當坐標',R('X = ',log('a','x'),'；Y = ',log('a','y'))),
    formula('直線還原',R('Y = mX + c ⇒ y = ',P('a','c'),P('x','m')))),
  '等比數列取對數':group('a 是首項、r 是公比，兩者都 > 0。所有 log 使用同一個有效底數。',
    formula('取 log 後的第 n 項',R('log(', 'a',P('r','n − 1'),') = log a + (n − 1)log r'))),
  '列清樣本空間':group('只有每個結果的機會相同，才可直接用數目相除。',
    formula('概率',F('符合要求的結果數','全部可能結果數'))),
  '至少一次用補事件':group('p 是每次成功的概率；下面的次方公式要求 n 次試驗互相獨立，而且每次成功概率相同。',
    formula('先算相反情況',R('P(至少一次) = 1 − P(一次也沒有)')),
    formula('n 次獨立試驗',R('P(至少一次) = 1 − ',P('(1 − p)','n')))),
  '不放回逐次更新':group('第二次的概率要按第一次抽走的物件更新。不同且互不重疊的完整路線才可相加。',
    formula('同一路線相乘',R('P(先 A 後 B) = P(A) × P(B｜A)'))),
  '獨立與互斥分清楚':group('∩ 表示兩件同時發生；∪ 表示至少一件發生。互斥時交集的概率是 0，不等於獨立。',
    formula('一般加法公式',R('P(A ∪ B) = P(A) + P(B) − P(A ∩ B)')),
    formula('只限獨立事件',R('P(A ∩ B) = P(A) × P(B)'))),
  '總和與加權平均':group('x 是數值，f 是該數值出現的次數；Σ 表示把各項加起來。總個數須 > 0。',
    formula('平均數',F('全部數值的總和','總個數')),
    formula('頻數表的平均數',F('Σfx','Σf')),
    formula('倒過來求總和',R('總和 = 平均數 × 個數'))),
  '排序後找中間':group('先由小至大排列。n 是總個數；「第幾個」指位置，不是數值。',
    formula('奇數個：中間的位置',F('n + 1','2')),
    formula('偶數個：中位數',F('中間兩個數值的和','2'))),
  '由中位數反推頻數':group('n 是總個數。偶數時，要取這兩個位置上的數值的平均，再核對題目的中位數。',
    formula('奇數個：看這個位置',F('n + 1','2')),
    formula('偶數個：看這兩個位置',R(F('n','2'),' 與 ',F('n','2'),' + 1'))),
  '先圈出同弧與切線':group('圓心角與圓周角必須對着同一段弧；切線須在接觸點與半徑相交。',
    formula('同弧的角',R('圓心角 = 2 × 圓周角')),
    formula('圓內接四邊形',R('一對對角的和 = 180°')),
    formula('切線與接觸點半徑',R('夾角 = 90°'))),
  '由圖讀取關係':group('找橫截距時令 y = 0，找縱截距時令 x = 0。',
    formula('x 軸交點',R('f(x) = 0')),
    formula('y 軸交點',R('y = f(0)'))),
  '對邊、鄰邊與斜邊':group('只用於直角三角形的銳角 θ；先按 θ 找對邊、鄰邊，直角對面才是斜邊。',
    formula('正弦',R('sin θ = ',F('對邊','斜邊'))),
    formula('餘弦',R('cos θ = ',F('鄰邊','斜邊'))),
    formula('正切',R('tan θ = ',F('對邊','鄰邊')))),
  '角與對邊成對':group('a、b、c 分別在角 A、B、C 的對面。求角時要檢查補角是否也是答案。',
    formula('正弦定理',R(F('a','sin A'),' = ',F('b','sin B'),' = ',F('c','sin C')))),
  '兩邊夾角或三邊':group('a 是角 A 的對邊，b、c 夾着角 A。',
    formula('餘弦定理',R('a² = b² + c² − 2bc cos A')),
    formula('求角先求 cos A',R('cos A = ',F('b² + c² − a²','2bc')))),
  '兩邊與夾角求面積':group('C 必須是邊 a、b 中間的夾角。',
    formula('三角形面積',F('ab sin C','2'))),
  '讀五數摘要':group('Q₁、Q₃ 分別是下、上四分位數；框長反映數值範圍，不是人數。',
    formula('框的長度',R('Q₃ − Q₁'))),
  '最大值減最小值':group('用實際出現的數值，不是頻數。',
    formula('分布域',R('最大值 − 最小值'))),
  '上下半部的中位數':group('Q₁、Q₃ 分別是下、上四分位數。',
    formula('四分位數間距',R('Q₃ − Q₁'))),
  '設未知數與列等式':group('這是一次方程 ax + b = c 的形式，a ≠ 0。先看題目能否寫成這種形式。',
    formula('兩邊減 b，再除以 a',R('x = ',F('c − b','a')))),
  '移項與反轉不等號':group('兩邊乘或除以負數才反方向；加減同一個數不用反方向。',
    formula('例如乘 −1',R('a < b ⇒ −a > −b'))),
  '辨清比較基數':group('r 用小數，例如 20% 寫成 0.2。原值是比較起點；百分比變化公式要求原值 > 0。',
    formula('增加',R('新值 = 原值 × (1 + r)')),
    formula('減少',R('新值 = 原值 × (1 − r)')),
    formula('百分比變化',R(F('新值 − 原值','原值'),' × 100%'))),
  '售價與標價互求':group('d 是實付比例，例如八折 d = 0.8；反求標價時 d > 0。',
    formula('打折後',R('售價 = 標價 × d')),
    formula('找回標價',R('標價 = ',F('售價','d')))),
  '成本、售價與盈虧':group('成本 > 0。盈利率及虧蝕率一般以成本為比較起點。',
    formula('盈利率',R(F('售價 − 成本','成本'),' × 100%')),
    formula('虧蝕率',R(F('成本 − 售價','成本'),' × 100%'))),
  '單利與複利':group('P 是本金，r 是每期利率的小數，n 是期數；利率與期數的時間單位要一致。',
    formula('單利本利和',R('P(1 + nr)')),
    formula('複利本利和',R('P',P('(1 + r)','n'))),
    formula('只求利息',R('本利和 − 本金'))),
  '代根求餘式':group('這裏除式是 x − a；如果是 x + a，要代入 −a。',
    formula('餘式定理',R('餘式 = f(a)')),
    formula('因式定理',R('x − a 是因式 ⇔ f(a) = 0'))),
  '正比先求常數':group('k 是不變的比例常數；次方要跟題目要求。',
    formula('y 與 x 成正比',R('y = kx')),
    formula('y 與 x² 成正比',R('y = kx²'))),
  '反比看乘積':group('k 是不變的比例常數，x ≠ 0。',
    formula('y 與 x 成反比',R('y = ',F('k','x'))),
    formula('等價寫法',R('xy = k')),
    formula('y 與 x² 成反比',R('y = ',F('k','x²')))),
  '部分變分分項列式':group('a、b 是各部分的常數。下面只是「固定部分＋與 x 成正比部分」的例子；若題目寫 x²，就要改用 x²。',
    formula('按每部分的關係相加',R('y = a + bx'))),
  '球體半徑與三次方':group('r 是半徑；若給直徑先除以 2。兩個球一定相似，體積比用半徑比的三次方。',
    formula('球體體積',R('V = ',F('4πr³','3'))),
    formula('兩球體積比',R(F('V₁','V₂'),' = ',P(bracket(F('r₁','r₂')),'3')))),
  '球面積分球計算':group('r 是半徑。每個球分開計算，不能把半徑相加後才平方。',
    formula('球的表面面積',R('S = 4πr²')),
    formula('兩球表面面積比',R(F('S₁','S₂'),' = ',P(bracket(F('r₁','r₂')),'2')))),
  '拆出平面直角三角形':group('先找垂足；θ 是斜線與底面投影的夾角，不是隨便選一條底邊的夾角。',
    formula('斜線長',root('垂直高² + 投影長²')),
    formula('線與平面夾角',R('tan θ = ',F('垂直高','投影長')))),
  '平移與倍乘數據':group('每個數都改成 ax + b；|a| 是 a 的絕對值，即去掉負號後的大小。',
    formula('平均數',R('新平均數 = a × 原平均數 + b')),
    formula('標準差',R('新標準差 = |a| × 原標準差')),
    formula('方差',R('新方差 = a² × 原方差'))),
  '由頻數表求標準差':group('x 是數值，f 是頻數，N = Σf > 0。Σ 是全部相加；fx² 只把 x 平方。這是分布標準差，不是除以 N − 1 的樣本標準差。',
    formula('平均數',R('μ = ',F('Σfx','N'))),
    formula('標準差',R('σ = ',root(R(F('Σfx²','N'),' − ',P(bracket(F('Σfx','N')),'2')))))),
  '相對平均數的位置':group('標準差必須 > 0。z 是標準分，正數代表高於平均，負數代表低於平均。',
    formula('標準分',R('z = ',F('分數 − 平均數','標準差')))),
  '選取而不計次序':group('n 個不同物件選 r 個，不計次序；n、r 是整數，0 ≤ r ≤ n。n! 是 n × (n − 1) × … × 1，0! = 1。',
    formula('組合',R('nCr = ',F('n!','r!(n − r)!')))),
  '組中值估算平均數':group('f 是該組人數；Σ 是把每組結果相加。因為不知道組內實際數值，結果只是估計。',
    formula('組中值',F('組的下限 + 組的上限','2')),
    formula('估計平均數',F('Σ(組中值 × f)','Σf'))),
  '相減還原頻數':group('N 是全部個數。從累積頻數曲線找位置後，要再向下讀橫軸的數值。',
    formula('單獨一組的頻數',R('這組累積頻數 − 上組累積頻數')),
    formula('Q₁、中位數、Q₃ 的累積位置',R(F('N','4'),'，',F('N','2'),'，',F('3N','4')))),
  '逐層解開目標字母':group('下面用 y = ax + b 示範，a ≠ 0；不是每題都直接套這一式。',
    formula('以 x 為主項',R('x = ',F('y − b','a')))),
  '固定差與項數':group('a 是首項，d 是公差，n 是正整數，Tₙ 是第 n 項，Sₙ 是前 n 項總和。',
    formula('第 n 項',R('Tₙ = a + (n − 1)d')),
    formula('前 n 項和',R('Sₙ = ',F('n(a + Tₙ)','2'))),
    formula('另一種寫法',R('Sₙ = ',F('n[2a + (n − 1)d]','2')))),
  '固定比與次方':group('a 是首項，r 是公比，n 是正整數。有限和的分數公式要求 r ≠ 1；無限和只在 |r| < 1 時使用。',
    formula('第 n 項',R('Tₙ = a',P('r','n − 1'))),
    formula('前 n 項和（r ≠ 1）',R('Sₙ = ',F(R('a(1 − ',P('r','n'),')'),'1 − r'))),
    formula('r = 1 時',R('Sₙ = na')),
    formula('無限項和（|r| < 1）',R('S∞ = ',F('a','1 − r')))),
  '找平行與角和':group('同旁內角相加為 180° 的關係，必須先有平行線。',
    formula('三角形內角和',R('A + B + C = 180°')),
    formula('一直線上的鄰角',R('總和 = 180°'))),
  '從取位找界限':group('這裏是正量的四捨五入；d 是相鄰刻度之差，例如最近 0.1 就用 d = 0.1。',
    formula('下界（包括）',R('記錄值 − ',F('d','2'))),
    formula('上界（不包括）',R('記錄值 + ',F('d','2')))),
  '用共同倍數表示':group('a、b 是正的份數。第一部分除以第二部分，和第一部分除以總數，是不同的分數。',
    formula('兩部分比較',R(F('第一部分','第二部分'),' = ',F('a','b'))),
    formula('第一部分佔全體',R(F('第一部分','總數'),' = ',F('a','a + b')))),
  '分解再通分':group('b、d 及原式的分母都不可為 0；分母乘多少，分子也要乘多少。',
    formula('分數相加',R(F('a','b'),' + ',F('c','d'),' = ',F('ad + bc','bd'))),
    formula('分數相減',R(F('a','b'),' − ',F('c','d'),' = ',F('ad − bc','bd')))),
  '分開處理兩個坐標':group('向右移 a、向上移 b；向左或向下可用負數表示。',
    formula('平移',R('(x,y) → (x + a,y + b)'))),
  '對稱軸與等距':group('先看清楚反射軸；反射後到軸的垂直距離不變。',
    formula('關於 x 軸',R('(x,y) → (x,−y)')),
    formula('關於 y 軸',R('(x,y) → (−x,y)')),
    formula('關於 y = x',R('(x,y) → (y,x)'))),
  '順時針與逆時針':group('以下只直接適用於繞原點 (0,0) 旋轉。',
    formula('逆時針 90°',R('(x,y) → (−y,x)')),
    formula('順時針 90°',R('(x,y) → (y,−x)')),
    formula('180°',R('(x,y) → (−x,−y)'))),
  '距離與方向角':group('此方法已標記超出課程範圍，只供歷年題參考。以下用向右為 0°、逆時針為正方向；r ≥ 0。',
    formula('轉直角坐標',R('x = r cos θ；y = r sin θ')),
    formula('離原點距離',R('r = ',root('x² + y²')))),
  '位置不同算不同':group('n 個不同物件選 r 個並排列，0 ≤ r ≤ n，兩者為整數。n! 表示由 n 乘至 1，0! = 1。',
    formula('排列',R('nPr = ',F('n!','(n − r)!')))),
  '角度對應比例':group('圓形圖的全體對應 360°；總數 > 0。',
    formula('某類佔的比例',F('該類角度','360°')),
    formula('求角度',R(F('該類數量','總數'),' × 360°'))),
  '時間單位先一致':group('速率、路程、時間的單位要配合；作分母的時間須 > 0。',
    formula('路程',R('速率 × 時間')),
    formula('速率',F('路程','時間')),
    formula('平均速率',F('全部路程','全部時間'))),
  '最小重合角':group('最小重合角要 > 0°；沒有小於一圈的重合角時，級數是 1。',
    formula('旋轉對稱級數',F('360°','最小重合角'))),
  '每個結果乘概率':group('x 是結果數值，p 是該結果的概率；Σ 表示全部相加。所有概率合計須為 1。',
    formula('期望值',R('E = Σ(xp)')),
    formula('扣除固定費用',R('淨收益期望值 = 收入期望值 − 費用'))),
  '用 i² = −1 化簡':group('a、b 是實數；a + bi 的共軛是 a − bi。相除時原分母不可為 0。',
    formula('虛數單位',R('i² = −1')),
    formula('乘共軛',R('(a + bi)(a − bi) = a² + b²')))
};

const escape=text=>String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tags={row:'mrow',frac:'mfrac',pow:'msup',root:'msqrt',sub:'msub',nthRoot:'mroot'};
export function mathMarkup(node){
  if(typeof node==='string')return `<mtext>${escape(node)}</mtext>`;
  const tag=tags[node.kind];
  if(!tag)throw new Error('Unknown formula node');
  return `<${tag}>${node.args.map(mathMarkup).join('')}</${tag}>`;
}
export function mathText(node){
  if(typeof node==='string')return node;
  const args=node.args.map(mathText);
  if(node.kind==='frac')return `（${args[0]}）除以（${args[1]}）`;
  if(node.kind==='pow')return `（${args[0]}）的（${args[1]}）次方`;
  if(node.kind==='root')return `根號（${args[0]}）`;
  if(node.kind==='nthRoot')return `（${args[0]}）的 ${args[1]} 次根`;
  if(node.kind==='sub')return `${args[0]} 下標 ${args[1]}`;
  return args.join('');
}
export function formulaPanel(technique){
  const group=formulaGroups[technique.title];
  if(!group)return '';
  return `<section class="formula-panel" aria-label="這裏會用到的公式"><h4>這裏會用到的公式</h4><p class="formula-note">${escape(group.note)}</p><small class="formula-help">分數由上除以下；長公式可左右滑動。</small>${group.items.map(formulaItem).join('')}</section>`;
}

function formulaItem(item){
  return `<figure class="formula-item"><figcaption>${escape(item.label)}</figcaption><div class="formula-scroll" tabindex="0" role="group" aria-label="${escape(item.label)}；公式較長時可左右捲動"><math xmlns="http://www.w3.org/1998/Math/MathML" display="block" aria-label="${escape(mathText(item.expression))}">${mathMarkup(item.expression)}</math></div></figure>`;
}

// Match each worked expression to its existing hint step; never reveal later steps early.
export const hintFormulas={
  '2012:8(a)':{2:[formula('先按對應邊配好分子、分母',R(F('AE','DE'),' = ',F('BE','CE')))]},
  '2014:9(b)':{1:[formula('大三角形的邊放在分子',R(F('AC','BC'),' = ',F('BC','DC'),' ⇒ ',F('25','20'),' = ',F('20','DC')))]},
  '2019:9(a)':{1:[formula('體積比用三次方',R(F('大球體積','小球體積'),' = ',P(bracket(F('2','1')),'3'),' = ',F('8','1')))],
    2:[formula('大球佔總體積的份數',R(F('大球體積','總體積'),' = ',F('8','8 + 1'),' = ',F('8','9')))]},
  '2019:9(b)':{1:[formula('先從小球體積找半徑',R(F('4πr³','3'),' = ',F('324π','9')))],
    2:[formula('表面面積比用二次方',R(F('大球表面面積','小球表面面積'),' = ',P(bracket(F('2','1')),'2'),' = ',F('4','1')))]},
  '2021:8(b)(ii)':{1:[formula('兩組對應邊保持同一次序',R(F('DB','AC'),' = ',F('DE','AE')))]},
  '2023:8(b)':{1:[formula('對應邊的比相同',R(F('AE','BE'),' = ',F('CE','DE'),' = ',F('10','15'),' = ',F('2','3')))]},
  '2025:8(b)':{1:[formula('依相似次序配邊',R(F('SW','VW'),' = ',F('UW','XW'),' ⇒ ',F('63','z'),' = ',F('z','7')))]},
  '2026:8(a)':{1:[formula('小三角形除以大三角形',R(F('BC','CE'),' = ',F('BD','EF'),' ⇒ ',F('x','x + 6'),' = ',F('8','x')))]},
  '2026:13(a)':{0:[formula('X 與 Y 的體積比',R(F('X 體積','Y 體積'),' = ',P(bracket(F('2','3')),'3'),' = ',F('8','27'))),
    formula('Z 與 Y 的體積比',R(F('Z 體積','Y 體積'),' = ',P(bracket(F('5','3')),'3'),' = ',F('125','27')))],
    1:[formula('Y 佔總體積',R(F('Y 體積','總體積'),' = ',F('27','8 + 27 + 125'),' = ',F('27','160')))]},
  '2026:13(b)(ii)':{0:[formula('表面面積比用二次方',R(F('Z 表面面積','Y 表面面積'),' = ',P(bracket(F('5','3')),'2'),' = ',F('25','9')))]}
};
export function hintFormulaPanel(id,step){
  const items=hintFormulas[id]?.[step];
  return items?`<div class="hint-formulas" data-formula-step="${step}">${items.map(formulaItem).join('')}</div>`:'';
}
